swagger: "2.0"
info:
  title: mobile API
  description: mobile has every tool to get any job done, so codename for the new
    mobile APIs.
  version: 1.0.0
  contact:
    email: astaxie@gmail.com
basePath: /v1
paths:
  /user/checkCode:
    post:
      tags:
      - user
      description: 验证登陆验证码接口
      operationId: UserController.登陆验证码
      parameters:
      - in: body
        name: data
        description: 请求参数
        required: true
        schema:
          $ref: '#/definitions/controllers.c_user.Code'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.c_user.Result'
        "404":
          description: 接口未找到
        "504":
          description: 接口超时
  /user/login:
    post:
      tags:
      - user
      description: 用户登陆接口
      operationId: UserController.登陆
      parameters:
      - in: body
        name: data
        description: 请求参数
        required: true
        schema:
          $ref: '#/definitions/models.SysUser'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.c_user.Result'
        "404":
          description: 接口未找到
        "504":
          description: 接口超时
definitions:
  controllers.c_user.Code:
    title: Code
    required:
    - code
    type: object
    properties:
      code:
        description: 短信验证码
        type: string
  controllers.c_user.Result:
    title: Result
    type: object
    properties:
      msg:
        type: string
      status:
        type: integer
        format: int64
  models.SysUser:
    title: SysUser
    required:
    - id
    - nickName
    - phone
    - createTime
    - updateTime
    type: object
    properties:
      createTime:
        description: 创建时间
        type: string
        format: datetime
      id:
        description: 用户id
        type: integer
        format: int64
      nickName:
        description: 用户昵称
        type: string
      phone:
        description: 手机号
        type: string
      updateTime:
        description: 更新时间
        type: string
        format: datetime
tags:
- name: user
  description: |
    UserController 用户控制器
