swagger: "2.0"
info:
  title: mobile API
  description: mobile has every tool to get any job done, so codename for the new
    mobile APIs.
  version: 1.0.0
  contact:
    email: astaxie@gmail.com
basePath: /v1
paths:
  /friends/addFriends:
    post:
      tags:
      - friends
      description: 添加好友
      operationId: FriendsController.添加好友
      parameters:
      - in: body
        name: data
        description: 请求参数
        required: true
        schema:
          $ref: '#/definitions/models.SysFriends'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.Result'
        "404":
          description: 接口未找到
        "504":
          description: 接口超时
  /friends/addFriendsAsk:
    post:
      tags:
      - friends
      description: 添加新的好友请求
      operationId: FriendsAskController.添加新的好友请求
      parameters:
      - in: body
        name: data
        description: 请求参数
        required: true
        schema:
          $ref: '#/definitions/models.SysFriendsAsk'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.FriendsAskResult'
        "404":
          description: 接口未找到
        "504":
          description: 接口超时
  /friends/getFriendsAskList:
    post:
      tags:
      - friends
      description: 获取好友列表
      operationId: FriendsAskController.获取好友列表
      parameters:
      - in: body
        name: data
        description: 请求参数
        required: true
        schema:
          $ref: '#/definitions/models.m_friendsAsk.SysFriendsAsk'
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/models.SysFriendsAsk'
        "404":
          description: 接口未找到
        "504":
          description: 接口超时
  /friends/getFriendsList:
    post:
      tags:
      - friends
      description: 获取好友列表
      operationId: FriendsController.获取好友列表
      parameters:
      - in: body
        name: data
        description: 请求参数
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/models.SysFriends'
        "404":
          description: 接口未找到
        "504":
          description: 接口超时
  /friends/putFriends:
    post:
      tags:
      - friends
      description: 修改好友信息
      operationId: FriendsController.修改好友信息
      parameters:
      - in: body
        name: data
        description: 请求参数
        required: true
        schema:
          $ref: '#/definitions/models.SysFriends'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.Result'
        "404":
          description: 接口未找到
        "504":
          description: 接口超时
  /friends/putFriendsAsk:
    post:
      tags:
      - friends
      description: 修改好友请求
      operationId: FriendsAskController.修改好友请求
      parameters:
      - in: body
        name: data
        description: 请求参数
        required: true
        schema:
          $ref: '#/definitions/models.SysFriendsAsk'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.Result'
        "404":
          description: 接口未找到
        "504":
          description: 接口超时
  /friends/queryFriend:
    post:
      tags:
      - friends
      description: 按名称搜索好友
      operationId: FriendsController.按名称搜索好友
      parameters:
      - in: body
        name: data
        description: 请求参数
        required: true
        schema:
          $ref: '#/definitions/models.SearchFriends'
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/models.SysFriends'
        "404":
          description: 接口未找到
        "504":
          description: 接口超时
  /msg/addMsg:
    post:
      tags:
      - msg
      description: 添加新消息接口
      operationId: MsgController.添加新消息接口
      parameters:
      - in: body
        name: data
        description: 请求参数
        required: true
        schema:
          $ref: '#/definitions/models.SysMsg'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.c_msg.Result'
        "404":
          description: 接口未找到
        "504":
          description: 接口超时
  /msg/getMsgList:
    post:
      tags:
      - msg
      description: 获取用户消息
      operationId: MsgController.获取用户消息
      parameters:
      - in: body
        name: data
        description: 请求参数
        required: true
        schema:
          $ref: '#/definitions/models.SysMsg'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.c_msg.Result'
        "404":
          description: 接口未找到
        "504":
          description: 接口超时
  /user/checkCode:
    post:
      tags:
      - user
      description: 验证登陆验证码接口
      operationId: UserController.登陆验证码
      parameters:
      - in: body
        name: data
        description: 请求参数
        required: true
        schema:
          $ref: '#/definitions/controllers.c_user.Code'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.c_user.LoginResult'
        "404":
          description: 接口未找到
        "504":
          description: 接口超时
  /user/login:
    post:
      tags:
      - user
      description: 用户登陆接口
      operationId: UserController.登陆
      parameters:
      - in: body
        name: data
        description: 请求参数
        required: true
        schema:
          $ref: '#/definitions/models.SysUser'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/controllers.c_user.Result'
        "404":
          description: 接口未找到
        "504":
          description: 接口超时
  /user/searchUser:
    post:
      tags:
      - user
      description: 搜索用户
      operationId: UserController.搜索用户
      parameters:
      - in: body
        name: data
        description: 请求参数
        required: true
        schema:
          $ref: '#/definitions/models.SearchUser'
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/models.SysUser'
        "404":
          description: 接口未找到
        "504":
          description: 接口超时
definitions:
  '{}':
    title: '{}'
    type: object
  controllers.FriendsAskResult:
    title: FriendsAskResult
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/models.SysFriendsAsk'
      msg:
        type: string
      status:
        type: integer
        format: int64
  controllers.Result:
    title: Result
    type: object
    properties:
      msg:
        type: string
      status:
        type: integer
        format: int64
  controllers.c_msg.Result:
    title: Result
    type: object
    properties:
      msg:
        type: string
      status:
        type: integer
        format: int64
  controllers.c_user.Code:
    title: Code
    required:
    - code
    type: object
    properties:
      code:
        description: 短信验证码
        type: string
  controllers.c_user.LoginResult:
    title: LoginResult
    type: object
    properties:
      data:
        $ref: '#/definitions/models.SysUser'
        description: 用户数据
      msg:
        type: string
      status:
        type: integer
        format: int64
      t:
        description: token
        type: string
  controllers.c_user.Result:
    title: Result
    type: object
    properties:
      msg:
        type: string
      status:
        type: integer
        format: int64
  models.SearchFriends:
    title: SearchFriends
    type: object
  models.SearchUser:
    title: SearchUser
    required:
    - phone
    type: object
    properties:
      phone:
        description: 用户手机号
        type: string
  models.SysFriends:
    title: SysFriends
    required:
    - id
    - sourceUid
    - targetUid
    - createTime
    - sourceName
    - sourceMark
    - targetName
    - targetMark
    - del
    type: object
    properties:
      createTime:
        description: 创建时间
        type: string
        format: datetime
      del:
        description: 删除标记
        type: integer
        format: int64
      id:
        description: 好友关系id
        type: integer
        format: int64
      sourceMark:
        description: 原用户备注名
        type: string
      sourceName:
        description: 原用户名
        type: string
      sourceUid:
        description: 源用户id
        type: integer
        format: int64
      targetMark:
        description: 目标用户备注名
        type: string
      targetName:
        description: 目标用户名
        type: string
      targetUid:
        description: 目标用户id
        type: integer
        format: int64
  models.SysFriendsAsk:
    title: SysFriendsAsk
    required:
    - id
    - sourceUid
    - targetUid
    - createTime
    - sourceName
    - targetName
    - del
    - isAgree
    type: object
    properties:
      createTime:
        description: 创建时间
        type: string
        format: datetime
      del:
        description: 软删除标记0：未删除，1：已删除
        type: integer
        format: int64
      id:
        description: 好友关系id
        type: integer
        format: int64
      isAgree:
        description: "是否同意请求0：未同意，1：同意，2：拒绝\t"
        type: integer
        format: int64
      sourceName:
        description: 原用户名
        type: string
      sourceUid:
        description: 源用户id
        type: integer
        format: int64
      targetName:
        description: 目标用户名
        type: string
      targetUid:
        description: 目标用户id
        type: integer
        format: int64
  models.SysMsg:
    title: SysMsg
    required:
    - id
    - friendsId
    - targetUid
    - sourceUid
    - content
    - createTime
    type: object
    properties:
      content:
        description: 消息内容
        type: string
      createTime:
        description: 创建时间
        type: string
        format: datetime
      friendsId:
        description: 好友关系id
        type: integer
        format: int64
      id:
        description: 消息id
        type: integer
        format: int64
      sourceUid:
        description: 源id
        type: integer
        format: int64
      targetUid:
        description: 目标id
        type: integer
        format: int64
  models.SysUser:
    title: SysUser
    required:
    - id
    - nickName
    - phone
    - createTime
    - updateTime
    type: object
    properties:
      createTime:
        description: 创建时间
        type: string
        format: datetime
      id:
        description: 用户id
        type: integer
        format: int64
      nickName:
        description: 用户昵称
        type: string
      phone:
        description: 手机号
        type: string
      updateTime:
        description: 更新时间
        type: string
        format: datetime
  models.m_friendsAsk.SysFriendsAsk:
    title: SysFriendsAsk
    required:
    - id
    - sourceUid
    - targetUid
    - createTime
    - sourceName
    - targetName
    - del
    - isAgree
    type: object
    properties:
      createTime:
        description: 创建时间
        type: string
        format: datetime
      del:
        description: 软删除标记0：未删除，1：已删除
        type: integer
        format: int64
      id:
        description: 好友关系id
        type: integer
        format: int64
      isAgree:
        description: "是否同意请求0：未同意，1：同意，2：拒绝\t"
        type: integer
        format: int64
      sourceName:
        description: 原用户名
        type: string
      sourceUid:
        description: 源用户id
        type: integer
        format: int64
      targetName:
        description: 目标用户名
        type: string
      targetUid:
        description: 目标用户id
        type: integer
        format: int64
tags:
- name: user
  description: |
    UserController 用户控制器
- name: friends
  description: |
    FriendsAskController 好友请求控制器
- name: msg
  description: |
    MsgController 消息控制器
